version: "3.9"

services:
  opentakserver:
    build: 
      context: .
      pull: false
    container_name: opentakserver
    volumes:
      - ots_certs:/home/ots/ots/ca/certs
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
      - "5672:5672"
      - "8000:8000/udp"
      - "8001:8001/udp"
      - "8080:8080"
      - "8088:8088"
      - "8089:8089"
      - "8443:8443"
      - "8446:8446"
      - "8883:8883"
      - "9997:9997"
      - "25672:25672"
      - "64738:64738"
      - "64738:64738/udp"
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    volumes:
      - ots_certs:/certs:ro
      - ./mediamtx.yml:/mediamtx.yml:ro
    ports:
      - "1935:1935"  # RTMP
      - "1936:1936"  # RTMPS
      - "8322:8322"  # RTSP(S)
      - "8554:8554"  # RTSP
      - "8888:8888"  # HLS
      - "8889:8889"  # WebRTC
      - "8890:8890/udp"  # SRT
      - "8189:8189/udp"  # WebRTC UDP
    environment:
      - MTX_PROTOCOLS=tcp
    restart: unless-stopped

volumes:
  ots_certs:
